# Generated by Django 5.1.1 on 2024-09-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodFacilityPermit',
            fields=[
                ('locationid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('applicant', models.CharField(max_length=500)),
                ('facility_type', models.CharField(max_length=200)),
                ('cnn', models.CharField(blank=True, max_length=100, null=True)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=500)),
                ('blocklot', models.CharField(blank=True, max_length=200, null=True)),
                ('block', models.CharField(blank=True, max_length=200, null=True)),
                ('lot', models.CharField(blank=True, max_length=200, null=True)),
                ('permit', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('food_items', models.TextField(blank=True, null=True)),
                ('x', models.CharField(blank=True, max_length=50, null=True)),
                ('y', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('schedule', models.URLField(blank=True, null=True)),
                ('dayshours', models.CharField(blank=True, max_length=500, null=True)),
                ('noi_sent', models.CharField(blank=True, max_length=200, null=True)),
                ('approved', models.DateTimeField(blank=True, null=True)),
                ('received', models.CharField(blank=True, max_length=100, null=True)),
                ('prior_permit', models.BooleanField(default=False)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('fire_prevention_districts', models.CharField(blank=True, max_length=50, null=True)),
                ('police_districts', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_districts', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_codes', models.CharField(blank=True, max_length=50, null=True)),
                ('neighborhoods_old', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
